#!/usr/bin/Rscript
###
### This script reads in satellite data (as GeoTIFF files) of elevation
### and forest cover, visualises these and converts them into a map file
### for the GeMM model.
###
### (c) Daniel Vedder 2020
### Licensed under the terms of the MIT license.
###

library(rgdal)
library(raster)
library(RStoolbox)
library(ggplot2)
library(rayshader)

##XXX Currently includes temp=293 (20°C -> annual mean temperature at Wundanyi,
## Mwalusepo et al. 2016). Would it be better to better to calculate temp from elevation?
## (though Zosterops are homoiothermic)

##XXX should we specify area (carrying capacity) in the map file?

simlength = 100
elevation_file = "taita_elevation.tif"
forest_file = "taita_forest_cover.tif"
habitat_file = "taita_habitats.tif"
above_ground_carbon_file = forest_file ##FIXME change as soon as the real data is available

image_output_file = "taita_map.jpg"
image_3D_output_file = "taita_hills_3D"
map_output_file = "taita_hills.map"

## Read in the GeoTIFF files and make sure they're workable
loadAllData = function(el_file=elevation_file, fo_file=forest_file,
                    ha_file=habitat_file, agc_file=above_ground_carbon_file)
{
    ## Read in the data
    print("Reading GeoTIFF files")
    elevation_data = raster(el_file)
    forest_data = raster(fo_file)
    habitat_data = raster(ha_file)
    agc_data = raster(agc_file)
    ## Do some sanity checks
    print("Checking for compatibility")
    if (!all(c(dim(elevation_data) == dim(forest_data),
               dim(forest_data) == dim(habitat_data),
               dim(habitat_data) == dim(agc_data)))) {
        print("Mismatching input data dimensions. Aborting.")
        return()
    }
    ## Return all raster objects
    return(c(elevation_data, forest_data, habitat_data, agc_data))
}

## Take in two rasters (elevation and forest cover) and create a 2D map image
##TODO add habitat map
visualiseMap = function(elevation, forest, out=image_output_file)
{
    print("Visualising 2D map")
    ggplot(data=forest) +
        geom_raster(aes(fill=taita_forest_cover, x=x, y=y)) +
        geom_contour(data=elevation, binwidth=200, colour="gray30",
                     aes(x=x, y=y, z=taita_elevation)) +
        scale_fill_gradient(high="forestgreen", low="greenyellow", na.value="gray90") +
        guides(fill=guide_legend(title="Forest cover")) +
        labs(caption="Taita Hills, Kenya") +
        coord_fixed() +
        theme_void()
    ggsave(out)
}

## Take in two rasters (elevation and forest cover) and create a 3D map image
visualise3DMap = function(elevation, forest, out=image_3D_output_file)
{
    print("Visualising 3D map")
    el_matrix = raster_to_matrix(elevation)
    fo_matrix = raster_to_matrix(forest)
    amb_shade = ambient_shade(el_matrix)
    ray_shade = ray_shade(el_matrix, sunangle=90)
    hillshade = sphere_shade(el_matrix, texture="imhof1")
    hillshade = add_shadow(add_shadow(hillshade, ray_shade), amb_shade)
    plot_3d(hillshade, el_matrix, zscale=30)
    ##TODO add overlay with forest data
    render_camera(-30,45,0.65)
    ##render_scalebar(limits=c(0,1), label_unit="km") #XXX doesn't work properly?
    render_compass()
    render_snapshot(out, title_color="white", title_bar_color="darkgreen",
                    title_text="TAITA HILLS, KENYA | Digital Elevation Model | USGS SRTM ")
}

## Take in the AGC raster and create a GeMM map file
convertMap = function(above_ground_carbon, run_length=simlength, out=map_output_file)
{
    if (typeof(above_ground_carbon) == "character") {
        above_ground_carbon = raster(above_ground_carbon)
    }
    print("Converting to GEMM input format")
    map_text = c("## ZOSTEROPS EXPERIMENT MAP", "",
                 "# Timesteps", toString(run_length), "",
                 "# Simulation arena - autogenerated by `map_creator.R`",
                 "# Source: Pellikka et al. 2018 (above ground carbon data)",
                 ##"# Sources: USGS LP-DAAC GFCC30TC (forest), CGIAR-CSI SRTM 90m DEM (elevation)",
                 "", "# <id> <x> <y> <temperature> <agc> [parameters]")
    nrows = nrow(above_ground_carbon)
    ncols = ncol(above_ground_carbon)
    i = 1:(nrows*ncols)
    x = rep(1:ncols, nrows)
    y = rep(1:nrows, each=ncols)
    map_text = c(map_text, paste(i, x, y, "temp=293", #XXX link temp to elevation?
                                 paste0("prec=", round(above_ground_carbon[i], 2)),
                                 sep="\t"))
                                 #"initpop", sep="\t"))
    writeLines(map_text, out)
    end = Sys.time()
}

runAll = function()
{
    data = loadAllData()
    elevation = data[1][[1]]
    forest = data[2][[1]]
    habitat = data[3][[1]]
    agc = data[4][[1]]
    ##visualiseMap(elevation, forest) #FIXME giving problems
    ##visualise3DMap(elevation, forest) #XXX seems to be better done by hand?
    convertMap(agc)
}

